# Generated by Django 5.2.1 on 2025-06-03 01:06

import backend.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=backend.accounts.models.user_profile_pic_path, verbose_name='profile picture'),
        ),
    ]
