# Generated by Django 5.2.1 on 2025-06-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(default=1, max_length=15, unique=True, verbose_name='phone number'),
            preserve_default=False,
        ),
    ]
