# Generated by Django 5.2.1 on 2025-06-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('dificuldade', models.CharField(choices=[('Baixa', 'Baixa'), ('Media', 'Média'), ('Alta', 'Alta')], max_length=10)),
                ('risco', models.CharField(choices=[('Baixo', 'Baixo'), ('Medio', 'Médio'), ('Alto', 'Alto')], max_length=10)),
                ('previsao_duracao', models.TimeField()),
                ('descricao_atividade', models.TextField(max_length=500)),
            ],
        ),
    ]
